name: Tests on Lambdatest

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write
env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
  IPHONE_MODEL: "iPhone 14 Pro"
  IOS_VERSION: 16.4

jobs:
  # Android:
  #   runs-on: macos-13
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: mskelton/setup-yarn@v1
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Run the tests
  #       run: |
  #         yarn androidtests
  #     - name: generate allure report
  #       run: |
  #         brew install allure
  #         allure generate allure-results
  #         zip -r allure-report.zip allure-report
  #     - name: Upload Allure Report as Pipeline Artifact
  #       if: always()
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: Allure Report
  #         path: "allure-report.zip"
  ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Export environment variables
        run: |
          export IPHONE_MODEL=$IPHONE_MODEL
          export IOS_VERSION=$IOS_VERSION

      - name: check simulator list
        run: xcrun simctl list

      - name: Start simulator
        run: |
          pwd
          ls -l 
          chmod a+x scripts/start_simu.sh
          scripts/start_simu.sh
      - name: Install appium
        run: |
          yarn add appium
          ln -fs /Users/runner/work/AppiumWebDriver.io/AppiumWebDriver.io/.npm-global/lib/node_modules/appium/build/lib/main.js /usr/local/bin/appium
          chmod +x /usr/local/bin/appium
          appium driver install xcuitest
      - name: Run Appium Server
        run: appium --log-timestamp --log appiumServer.log &
      - name: Run the tests
        run: |
          yarn iostestslocal
      - name: generate allure report
        run: |
          brew install allure
          allure generate allure-results
          zip -r allure-report.zip allure-report
      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: "allure-report.zip"
