name: Tests on Lambdatest

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Android:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      # - name: Run the tests
      #   run: |
      #     yarn androidtests
      - name: generate allure report
        run: |
          brew install allure
          echo 'test............'
          pwd
          ls -l
          # allure generate allure-results
      # - name: Upload Allure Summary Report as Pipeline Artifact
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Allure Report
      #     path: "allure-report/index.html"
