name: Tests on Lambdatest

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

env:
  IPHONE_MODEL: ${{ inputs.IOS_simulator }}
  IOS_VERSION: 16.2
  API_LEVEL: 30
  EMULATOR_NAME: Nexus
  EMULATOR_DEVICE: ${{ inputs.android_emulator }}
  EMULATOR_VERSION: 12
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  ANDROID_BUILD_TOOLS_VERSION: 33.0.2
  ANDROID_SDK_PACKAGES: system-images;android-30;google_apis;x86_64 platforms;android-30 build-tools;33.0.2 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  BOOT_TIMEOUT: 700

jobs:
  Android:
    runs-on: macos-13
    strategy:
      matrix:
        os: [Android]
        emulator_name: [$EMULATOR_NAME]
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - name: Run the tests
        run: |
          yarn androidtests
      - name: Generate report
        if: always()
        run: |
          npx allure generate report/allure-results

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./allure-report"

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v2
